<?xml version="1.0"?>
<robot name="mini_max">

  <!-- size properties -->
  <property name="material_thickness" value="0.00476" />
  <property name="standoff_height" value="0.04445" />
  <property name="body_height" value="0.3302" />
  <property name="neck_height" value="0.0857" />

  <include filename="$(find turtlebot_arm_description)/urdf/arm.xacro" />

  <!-- colors -->
  <material name="grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <!-- create base -->
  <property name="create_radius" value="0.16495" />
  <property name="create_height" value="0.0611632" />
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
              iyy="0.0001" iyz="0.0" 
              izz="0.0001" />
    </inertial>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 0.017" rpy="0 0 0" />        
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0.0308" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 0.0308" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://turtlebot_description/meshes/create_body.dae"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0308" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.0611632" radius="0.16495"/>
      </geometry>
    </collision>
  </link>

  <joint name="column_joint" type="fixed">
    <parent link="base_link" />
    <child link="column_link" />
    <origin xyz="0.0349 0 ${create_height+standoff_height+material_thickness+body_height+material_thickness}"/>
  </joint>
  <link name="column_link" >
    <visual>
      <origin xyz="0 0 0" rpy="3.14 0 -1.57" />
      <geometry>
        <mesh filename="package://mini_max_defs/meshes/body.stl"  />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="3.14 0 -1.57" />
      <geometry>
        <mesh filename="package://mini_max_defs/meshes/body.stl"  />
      </geometry>
    </collision>
  </link>

  <!-- head w/ kinect, pan/tilt -->
  <bioloid_F3_revolute parent="column_link" name="head_pan" color="white" vlimit="1.571" llimit="-2.0" ulimit="2.0">
    <origin xyz="0 0 0" rpy="${M_PI} 0 ${M_PI}"/>
  </bioloid_F3_revolute>
  <dynamixel_AX12_fixed parent="head_pan_link" name="head_pan_servo">
    <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
  </dynamixel_AX12_fixed>
  <bioloid_F2_revolute parent="head_pan_servo_link" name="head_tilt" color="white" vlimit="1.571" llimit="-2.671" ulimit="2.671">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </bioloid_F2_revolute>

  <joint name="head_sensor_frame_joint" type="fixed">
    <origin xyz="0.03 0 0.075" rpy="0 0 0" />     
    <parent link="head_tilt_link" />
    <child link="head_sensor_frame" />
  </joint>

  <link name="head_sensor_frame">
    <inertial>
      <mass value="0.00001" />
      <origin xyz="0 0 0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 0 " rpy="0 0 0" />
      <geometry>
        <mesh filename="package://turtlebot_description/meshes/kinect.dae"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.0730 .2760 0.0720"/>
      </geometry>
    </collision>
  </link>

  <!-- add arm and gripper -->
  <turtlebot_arm parent="base_link" color="white" gripper_color="grey">
    <origin xyz="0.104775 -0.0381 ${create_height+standoff_height+material_thickness}"/>
  </turtlebot_arm>

</robot>
