base_link: torso_link

sensors:

  chains:
    arm_chain:
      root: torso_link
      tip: arm_wrist_roll_link
      cov:
       joint_angles: [0.001, 0.001, 0.001, 0.001, 0.001]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0]
    head_chain:
      root: head_link
      tip: head_tilt_link
      cov:
       joint_angles: [0.001, 0.001]
      gearing: [1.0, 1.0]

  rectified_cams:
    head_camera:
      chain_id: head_chain  #TODO: get rid of this
      frame_id: head_camera_rgb_optical_frame
      baseline_shift: 0.0
      f_shift: 0.0
      cx_shift: 0.0
      cy_shift: 0.0
      cov: {u: 0.25, v: 0.25}

  tilting_lasers: {}

checkerboards:
  small_cb_4x5:
    corners_x: 4
    corners_y: 5
    spacing_x: 0.0245
    spacing_y: 0.0245

transforms:
  arm_chain_cb:   [ .25, 0, 0, -pi/2, 0, 0]

