
# ----- Arm -----
arm_chain:
  settler_config:  /arm_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - arm_lift_joint
        - arm_shoulder_pan_joint
        - arm_shoulder_lift_joint
        - arm_elbow_flex_joint
        - arm_wrist_flex_joint
        - arm_wrist_roll_joint
        tolerances:
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        max_step:   1.0
        cache_size: 1500

# ----- Head -----
head_chain:
  settler_config:  /head_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - head_pan_joint
        - head_tilt_joint
        tolerances:
        - 0.01
        - 0.01
        max_step:   1.0
        cache_size: 1500
