arm_controller:
  topic: arm_controller/command
  joint_names:
  - arm_lift_joint
  - arm_shoulder_pan_joint
  - arm_shoulder_lift_joint
  - arm_elbow_flex_joint
  - arm_wrist_flex_joint
  - arm_wrist_roll_joint

head_traj_controller:
  topic: head_controller/command
  joint_names:
  - head_pan_joint
  - head_tilt_joint
