<?xml version="1.0"?>
<robot>

  <!-- cosmetics -->
  <macro name="head_mount" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="-1.57 3.14 0" />
        <geometry>
          <mesh filename="package://maxwell_defs/meshes/head_mount.stl" scale="1 1 1"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.57 0" />
        <geometry>
          <box size="0.0865 0.0047625 0.038"/>
        </geometry>
      </collision>
    </link>
  </macro>


  <!-- origin is center of head tilt rotation -->
  <macro name="maxwell_head" params="name parent *origin">

    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link"/>
    <head_mount name="${name}_left_mount" parent="${name}_link">
      <origin xyz="0 0.01905 0" rpy="0 0 0"/>
    </head_mount>
    <head_mount name="${name}_right_mount" parent="${name}_link">
      <origin xyz="0 ${-0.01905-0.003175} 0" rpy="0 0 0"/>
    </head_mount>

    <!-- Head pan -->
    <dynamixel_ax12_pan parent="${name}_link" name="${name}_pan_servo" color="Black">
      <origin xyz="0.010 0 0.0254" rpy="0 0 0"/>
    </dynamixel_ax12_pan>
    <ax12_side_revolute parent="${name}_pan_servo_link" name="${name}_pan" llimit="-2.617" ulimit="2.617" vlimit="1.0" color="Orange">
      <origin xyz="0 0 ${AX12_WIDTH/2}" rpy="0 0 0"/>
    </ax12_side_revolute>

    <ax12_side_fixed parent="${name}_pan_servo_link" name="${name}_tilt_left_side" color="Black">
      <origin xyz="-0.015 ${-AX12_WIDTH/2} 0" rpy="1.57 0 0"/>
    </ax12_side_fixed>
    <ax12_side_fixed parent="${name}_pan_servo_link" name="${name}_tilt_right_side" color="Black">
      <origin xyz="-0.015 ${AX12_WIDTH/2} 0" rpy="-1.57 0 0"/>
    </ax12_side_fixed>

    <!-- Head tilt -->
    <dynamixel_ax12_tilt parent="${name}_pan_link" name="${name}_tilt_servo" color="Black">
      <origin xyz="0 0 ${AX12_HEIGHT+0.003}" rpy="0 0 0"/>
    </dynamixel_ax12_tilt>
    <ax12_hinge_revolute parent="${name}_tilt_servo_link" name="${name}_tilt" llimit="-2.617" ulimit="2.617" vlimit="1.0" color="Orange">
     <origin xyz="0 0 0" rpy="0 0 0"/>
    </ax12_hinge_revolute>

    <!-- Head sensor frame -->
    <joint name="${name}_sensor_frame_joint" type="fixed">
      <origin xyz="0 0 0.0425"/>
      <parent link="${name}_tilt_link"/>
      <child link="${name}_sensor_frame"/>
    </joint>
    <link name="${name}_sensor_frame">
      <visual>
        <origin xyz="-0.03 0 0" rpy="0 0 -1.57" />
        <geometry>
          <mesh filename="package://maxwell_defs/meshes/kinect.stl" />
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.064 0.28 0.04"/>
        </geometry>
      </collision>
    </link>

    <!-- Openni Link -->
    <joint name="openni_camera_joint" type="fixed">
      <origin xyz="${calib_cam_x} ${calib_cam_y} ${calib_cam_z}" rpy="${calib_cam_rr} ${calib_cam_rp} ${calib_cam_ry}" />
      <parent link="${name}_sensor_frame"/>
      <child link="openni_camera"/>
    </joint>
    <link name="openni_camera"/>

  </macro>

</robot>
