<?xml version="1.0"?>
<robot name="maxwell" >

  <property name='calib_cam_x' value='0.00468423' />
  <property name='calib_cam_y' value='0.0060704' />
  <property name='calib_cam_z' value='-0.0306572' />
  <!--<property name='calib_cam_z' value='0.0118428' />-->
  <property name='calib_cam_rr' value='-0.024976' />
  <property name='calib_cam_rp' value='-0.0119664' />
  <property name='calib_cam_ry' value='0.0228755' />

  <!--
  <property name="calib_cam_x" value="0" />
  <property name="calib_cam_y" value="0" />
  <property name="calib_cam_z" value="0" />
  <property name="calib_cam_rr" value="0" />
  <property name="calib_cam_rp" value="0" />
  <property name="calib_cam_ry" value="0" />
  -->

  <property name="arm_height" value="0.6619375 " /> <!-- deck to arm_link -->
  <property name="column_height" value="1.171575" /> <!-- deck to top of 80/20: 46-1/8" -->
  
  <include filename="$(find maxwell_defs)/urdf/hardware/ax12.xacro" />
  <include filename="$(find maxwell_defs)/urdf/hardware/rx64.xacro" />
  
  <!-- The following included files set up definitions of parts of the robot body -->
  <include filename="$(find maxwell_defs)/urdf/base.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/torso.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/arm.urdf.xacro" />
  <!--<include filename="$(find maxwell_defs)/urdf/gripper.urdf.xacro" />-->
  <include filename="$(find maxwell_defs)/urdf/head.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/materials.urdf.xacro" />

  <!-- Now we can start using the macros included above to define the actual Maxwell -->
  <armadillo_base name="base"/>

  <!-- Add Torso Upright -->
  <maxwell_torso name="torso" parent="base">
    <origin xyz="-0.00635 0 ${base_size_z}"/>
  </maxwell_torso>

  <!-- Arm -->
  <maxwell_arm name="arm" parent="torso">
    <origin xyz="0.0608 0 ${arm_height}"/>
  </maxwell_arm>

  <!-- Gripper -->
  <!--<maxwell_gripper name="gripper" parent="arm_wrist_roll">
    <origin xyz="0.150 0 0" /> 
  </maxwell_gripper>-->

  <!-- Kinect head -->
  <maxwell_head name="head" parent="torso_link">
    <!--<origin xyz="0.0157 0 ${column_height}"/>-->
    <!--<origin xyz="${0.0157+0.05715/2} -0.005 ${column_height+0.0460375}"/>-->
    <origin xyz="0 0 ${column_height+0.0270375}"/>
  </maxwell_head>

</robot>
