<?xml version="1.0"?>
<robot name="maxwell" >

  <property name='calib_cam_x' value='0.00259672' />
  <property name='calib_cam_y' value='0.0307021' />
  <property name='calib_cam_z' value='0.0133213' />
  <property name='calib_cam_rr' value='-0.0829819' />
  <property name='calib_cam_rp' value='0.00482693' />
  <property name='calib_cam_ry' value='0.0643122' />

  <property name="arm_height" value="0.7239"/> <!-- deck to arm_link at max height-->
  <property name="column_height" value="1.160075" /> <!-- deck to top of 80/20: 46-1/8" -->
  
  <include filename="$(find maxwell_defs)/urdf/hardware/ax12.xacro" />
  <include filename="$(find maxwell_defs)/urdf/hardware/rx64.xacro" />
  <include filename="$(find maxwell_defs)/urdf/sensors/xtion_camera.xacro" />
  
  <!-- The following included files set up definitions of parts of the robot body -->
  <include filename="$(find maxwell_defs)/urdf/base.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/torso.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/arm.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/gripper.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/head.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/materials.urdf.xacro" />

  <!-- Now we can start using the macros included above to define the actual Maxwell -->
  <armadillo_base name="base" color="Orange"/>

  <!-- Add Torso Upright -->
  <maxwell_torso name="torso" parent="base_link">
    <origin xyz="-0.00635 0 ${base_size_z+arm_height}" rpy="0 0 0"/>
  </maxwell_torso>

  <!-- Live joint between torso and arm -->
  <joint name="arm_lift_joint" type="prismatic">
    <axis xyz="0 0 1" />
    <limit lower="-0.464" upper="0" effort="30" velocity="0.0508"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="torso_link"/>
    <child link="arm_lift_link"/>
  </joint>
  <link name="arm_lift_link"/>

  <!-- Arm -->
  <maxwell_arm name="arm" parent="arm_lift_link">
    <origin xyz="0.0611 0 0" rpy="0 0 0"/>
  </maxwell_arm>

  <!-- Gripper -->
  <maxwell_gripper name="gripper" parent="arm_wrist_roll" color="Orange">
    <origin xyz="0 0 0" rpy="0 0 0" /> 
  </maxwell_gripper>

  <!-- Head -->
  <maxwell_head name="head" parent="torso_link" color="Orange">
    <origin xyz="0 0 ${column_height-arm_height}" rpy="0 0 0"/>
  </maxwell_head>
  <xtion_camera name="head_camera" parent="head_tilt_link">
    <origin xyz="0 0 0.026" rpy="0 0 0"/>
  </xtion_camera>

</robot>
