<?xml version="1.0"?>
<robot name="maxwell" >

  <!-- height properties -->
  <property name="torso_height" value="0.6" />
  <property name="column_height" value="1.17475" />
  
  <!-- The following included files set up definitions of parts of the robot body -->
  <include filename="$(find maxwell_defs)/urdf/base.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/torso.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/arm.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/gripper.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/head.urdf.xacro" />
  <include filename="$(find maxwell_defs)/urdf/materials.urdf.xacro" />

  <!-- Now we can start using the macros included above to define the actual Maxwell -->
  <armadillo_base name="base"/>

  <!-- Add Torso Upright -->
  <maxwell_torso name="torso" parent="base">
    <origin xyz="-0.00635 0 ${0.1397+torso_height}"/>
  </maxwell_torso>

  <!-- Arm -->
  <maxwell_arm name="arm" parent="torso">
    <origin xyz="0.0608 0 0.0"/>
  </maxwell_arm>

  <!-- Gripper -->
  <maxwell_gripper name="gripper" parent="arm_wrist_roll">
    <origin xyz="0.100 0 0" /> 
  </maxwell_gripper>

  <!-- Kinect head -->
  <maxwell_head name="head" parent="torso">
    <origin xyz="0.0157 0 ${column_height-torso_height}"/>
  </maxwell_head>

</robot>
