joint_limits:
  arm_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  arm_wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false