min_sensor_dist: .35
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: arm_shoulder_pan_servo_link
    padding: .03
  - name: arm_shoulder_pan_link
    padding: .03
  - name: arm_shoulder_lift_servo_link
    padding: .03
  - name: arm_shoulder_lift_link
    padding: .03
  - name: arm_elbow_flex_link
    padding: .03
  - name: arm_forearm_link
    padding: .03
  - name: arm_wrist_flex_servo_link
    padding: .03
  - name: arm_wrist_flex_link
    padding: .03
  - name: arm_wrist_roll_link
    padding: .03
  - name: gripper_F6_1_link
    padding: .03
  - name: gripper_F6_2_link
    padding: .03
  - name: gripper_F6_3_link
    padding: .03
  - name: gripper_F6_4_link
    padding: .03
  - name: left_gripper_servo_link
    padding: .03
  - name: right_gripper_servo_link
    padding: .03
  - name: l_gripper_link
    padding: .03
  - name: r_gripper_link
    padding: .03
  - name: left_gripper_finger_link
    padding: .03
  - name: right_gripper_finger_link
    padding: .03

