<?xml version="1.0"?>
<robot>

  <!-- origin is center of head tilt rotation -->
  <macro name="maxwell_head" params="name parent *origin">

    <!-- Head pan -->
    <dynamixel_ax12_pan parent="${parent}" name="${name}_pan_servo" color="Black">
      <insert_block name="origin" />
    </dynamixel_ax12_pan>
    <ax12_side_revolute parent="${name}_pan_servo_link" name="${name}_pan" llimit="-2.617" ulimit="2.617" color="Orange">
      <origin xyz="0 0 ${AX12_WIDTH/2}" rpy="0 0 0"/>
    </ax12_side_revolute>

    <ax12_side_fixed parent="${name}_pan_servo_link" name="${name}_tilt_left_side" color="Black">
      <origin xyz="-0.015 ${-AX12_WIDTH/2} 0" rpy="1.57 0 0"/>
    </ax12_side_fixed>
    <ax12_side_fixed parent="${name}_pan_servo_link" name="${name}_tilt_right_side" color="Black">
      <origin xyz="-0.015 ${AX12_WIDTH/2} 0" rpy="-1.57 0 0"/>
    </ax12_side_fixed>

    <!-- Head tilt -->
    <dynamixel_ax12_tilt parent="${name}_pan_link" name="${name}_tilt_servo" color="Black">
      <origin xyz="0 0 ${AX12_HEIGHT+0.003}" rpy="0 0 0"/>
    </dynamixel_ax12_tilt>
    <ax12_hinge_revolute parent="${name}_tilt_servo_link" name="${name}_tilt" color="Orange">
     <origin xyz="0 0 0" rpy="0 0 0"/>
    </ax12_hinge_revolute>

    <!-- Head sensor frame -->
    <joint name="${name}_sensor_frame_joint" type="fixed">
      <origin xyz="0 0 0.0425"/>
      <parent link="${name}_tilt_link"/>
      <child link="${name}_sensor_frame"/>
    </joint>
    <link name="${name}_sensor_frame">
      <visual>
        <origin xyz="-0.03 0 0" rpy="0 0 -1.57" />
        <geometry>
          <mesh filename="package://maxwell_defs/meshes/kinect.stl" />
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.064 0.28 0.04"/>
        </geometry>
      </collision>
    </link>

    <!-- Openni Link -->
    <joint name="openni_camera_joint" type="fixed">
      <origin xyz="${calib_cam_x} ${calib_cam_y} ${calib_cam_z}" rpy="${calib_cam_rr} ${calib_cam_rp} ${calib_cam_ry}" />
      <parent link="${name}_sensor_frame"/>
      <child link="openni_camera"/>
    </joint>
    <link name="openni_camera"/>

  </macro>

</robot>
