group: "Arm"
prompt: "Please put the checkerboard in the hand (open/close the gripper with the joystick's square/circle buttons). press <enter> to continue..."
finish: "Skipping arm samples"
repeat: False
